# Generated by Django 4.2.1 on 2024-01-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                ("categoryId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "categoryName",
                    models.CharField(default=None, max_length=45, null=True),
                ),
                ("categoryCount", models.IntegerField(default=None, null=True)),
            ],
            options={
                "db_table": "blog_category_seq",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("roleId", models.AutoField(primary_key=True, serialize=False)),
                ("roleName", models.CharField(default=None, max_length=45, null=True)),
            ],
            options={
                "db_table": "role_seq",
            },
        ),
        migrations.CreateModel(
            name="TouristType",
            fields=[
                ("typeId", models.AutoField(primary_key=True, serialize=False)),
                ("typeName", models.CharField(default=None, max_length=45, null=True)),
                ("typeCount", models.IntegerField(default=None, null=True)),
            ],
            options={
                "db_table": "tourist_type_seq",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(default=None, max_length=45, null=True)),
                (
                    "userPassword",
                    models.CharField(default=None, max_length=45, null=True),
                ),
                ("userBirthyear", models.IntegerField(default=None, null=True)),
                ("userPhone", models.CharField(default=None, max_length=45, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.role"
                    ),
                ),
            ],
            options={
                "db_table": "user_seq",
            },
        ),
        migrations.CreateModel(
            name="Tourist",
            fields=[
                ("tourist_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "touristName",
                    models.CharField(default=None, max_length=45, null=True),
                ),
                ("touristDescription", models.TextField()),
                (
                    "touristLocation",
                    models.CharField(default=None, max_length=45, null=True),
                ),
                (
                    "touristImage",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.touristtype",
                    ),
                ),
            ],
            options={
                "db_table": "tourist_seq",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("blogId", models.AutoField(primary_key=True, serialize=False)),
                ("blogTitle", models.CharField(default=None, max_length=45, null=True)),
                ("blogDate", models.DateTimeField()),
                (
                    "blogAuthor",
                    models.CharField(default=None, max_length=45, null=True),
                ),
                ("blogContent", models.TextField(default=None, null=True)),
                (
                    "blogImage",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.blogcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.user"
                    ),
                ),
            ],
            options={
                "db_table": "blog_seq",
            },
        ),
    ]
