# Generated by Django 4.2.1 on 2024-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blogCount",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
