# Generated by Django 4.2.1 on 2024-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_user_blogcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourist",
            name="touristLocation",
            field=models.CharField(default=None, max_length=145, null=True),
        ),
        migrations.AlterField(
            model_name="tourist",
            name="tourist_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Tourist ID"
            ),
        ),
    ]
