# Generated by Django 4.2.1 on 2024-01-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_alter_tourist_touristlocation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="user",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
