# Generated by Django 4.2.1 on 2024-01-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0005_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
